import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/cors/Header'
import Hero from '@/components/homePage/Hero'
import PetsForAdoption from '@/components/homePage/PetsForAdoption'
import Services from '@/components/homePage/Services'
import PetAdvices from '@/components/homePage/PetAdvices'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="HomePage">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='Shape1'></div>
      <Header/>
      <Hero/>
      <PetsForAdoption/>
      <Services/>
      <PetAdvices/>
    </div>
  )
}
