import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/cors/Header'
import Hero from '@/components/homePage/Hero'
import PetsForAdoption from '@/components/homePage/PetsForAdoption'
import Services from '@/components/homePage/Services'
import PetAdvices from '@/components/homePage/PetAdvices'
import About from '@/components/homePage/About'

import { Router, useRouter } from 'next/router'
import Footer from '@/components/cors/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const { route } = router;

  return (
    <div className="HomePage">
      <Head>
        <title>{route === '/' ? 'Molly' : `Molly - ${route}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link  href="/logo.svg" rel="icon"  type="image/svg+xml"/>
      </Head>
      <div className='Shape1'></div>
      <Header/>
      <div className="sections">
      <Hero/>
      <PetsForAdoption/>
      <Services/>
      <PetAdvices/>
      <About/>
      <Footer/>
      </div>
    </div>
  )
}
